// FIX: Created UI_TEXT constants object to resolve multiple "is not a module" and "Cannot find name" errors across the application.
export const UI_TEXT = {
  inventory: 'Inventaris',
  dashboard: 'Dasbor',
  transactions: 'Transaksi',
  users: 'Pengguna',
  settings: 'Pengaturan Akun & Sistem',
  createTransaction: 'Buat Transaksi',
  categories: 'Kategori',
  profile: 'Profil Saya',
  logout: 'Keluar',
  totalItems: 'Total Barang',
  lowStockItems: 'Stok Menipis',
  itemsOut: 'Barang Keluar',
  itemsIn: 'Barang Masuk',
  normalItems: 'Kondisi Normal',
  damagedItems: 'Kondisi Rusak',
  inventoryByCategory: 'Inventaris per Kategori',
  recentTransactions: 'Transaksi Terkini',
  searchDevice: 'Cari perangkat...',
  addDevice: 'Tambah Perangkat',
  export: 'Ekspor',
  name: 'Nama Perangkat',
  category: 'Kategori',
  deviceBrand: 'Merek',
  quantity: 'Jumlah',
  deviceStatus: 'Status',
  deviceCondition: 'Kondisi',
  action: 'Aksi',
  edit: 'Ubah',
  delete: 'Hapus',
  transactionHistory: 'Riwayat Transaksi',
  startDate: 'Tanggal Mulai',
  endDate: 'Tanggal Akhir',
  transactionType: 'Tipe Transaksi',
  date: 'Tanggal',
  handledBy: 'Ditangani Oleh',
  sourceOrDestination: 'Sumber/Tujuan',
  senderOrRecipient: 'Pengirim/Penerima',
  incoming: 'Masuk',
  outgoing: 'Keluar',
  loginTitle: 'Masuk ke Akun Anda',
  loginWelcome: 'Selamat datang kembali! Silakan pilih peran Anda.',
  email: 'Alamat Email',
  password: 'Kata Sandi',
  loginAsAdmin: 'Masuk sebagai Administrator',
  loginAsViewer: 'Masuk sebagai Staf Gudang',
  insufficientStockError: 'Stok tidak mencukupi untuk transaksi ini.',
  deviceRegistrationNumber: 'Nomor Registrasi Perangkat',
  transactionSummary: 'Ringkasan Transaksi',
  initialStock: 'Stok Awal',
  transactionAmount: 'Jumlah Transaksi',
  finalStock: 'Stok Akhir',
  addCategory: 'Tambah Kategori',
  categoryName: 'Nama Kategori',
  deleteCategory: 'Hapus Kategori',
  confirmDeleteCategoryMessage: 'Apakah Anda yakin ingin menghapus kategori "{categoryName}"? Tindakan ini tidak dapat diurungkan.',
  profileUpdatedSuccessfully: 'Profil berhasil diperbarui!',
  passwordUpdatedSuccessfully: 'Kata sandi berhasil diperbarui!',
  passwordsDoNotMatch: 'Kata sandi baru tidak cocok.',
  profileInformation: 'Informasi Profil',
  userName: 'Nama',
  userEmail: 'Email',
  userRole: 'Peran',
  saveChanges: 'Simpan Perubahan',
  changePassword: 'Ubah Kata Sandi',
  currentPassword: 'Kata Sandi Saat Ini',
  newPassword: 'Kata Sandi Baru',
  confirmNewPassword: 'Konfirmasi Kata Sandi Baru',
  updatePassword: 'Perbarui Kata Sandi',
  editDevice: 'Ubah Perangkat',
  description: 'Deskripsi',
  editCategory: 'Ubah Kategori',
  addUser: 'Tambah Pengguna',
  editUser: 'Ubah Pengguna',
  searchUser: 'Cari pengguna...',
  deleteUser: 'Hapus Pengguna',
  confirmDeleteUserMessage: 'Apakah Anda yakin ingin menghapus pengguna "{userName}"? Tindakan ini tidak dapat diurungkan.',
  cancel: 'Batal',
  deviceDetails: 'Detail Perangkat',
  transactionDetails: 'Detail Transaksi',
  backupSettings: 'Pengaturan Cadangan Sistem',
  enableScheduledBackups: 'Aktifkan Cadangan Terjadwal',
  backupFrequency: 'Frekuensi Cadangan',
  daily: 'Harian',
  weekly: 'Mingguan',
  monthly: 'Bulanan',
  backupTime: 'Waktu Cadangan',
  backupDestination: 'Tujuan Cadangan',
  local: 'Lokal',
  cloud: 'Cloud',
  settingsSaved: 'Pengaturan berhasil disimpan!',
};